// Fixed analog grain across the whole viewport. The noise is generated by an
// inline SVG feTurbulence rather than a bitmap, so it costs nothing to load and
// stays crisp at any DPR. pointer-events-none so it never eats a click.
const NOISE = encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180">
    <filter id="n">
      <feTurbulence type="fractalNoise" baseFrequency="0.82" numOctaves="4" stitchTiles="stitch"/>
      <feColorMatrix type="saturate" values="0"/>
    </filter>
    <rect width="180" height="180" filter="url(#n)"/>
  </svg>`.replace(/\s+/g, ' '),
)

export default function GrainOverlay() {
  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-0 z-[100] opacity-[0.045]"
      style={{
        backgroundImage: `url("data:image/svg+xml,${NOISE}")`,
        backgroundRepeat: 'repeat',
      }}
    />
  )
}
